### ISSUE TITLE
Agregar banner con imagen en home

### ISSUE THREAD

**Issue by mrichart** [solidaridadUY/solidaridaduy.github.io#38]
La idea es agregar una imagen de fondo de los filtros junto con un breve texto explicativo de la plataforma.

**Comment by mrichart** [comment]
En el branch home-banner hay una propuesta inicial.
Ahora hay una imagen de google y falta definir el texto

**Comment by despinoUY** [comment]
Me gusta mucho la propuesta. Le sacaría un poco de padding-top al search-container y eliminaría el padding-bottom. Eso se lo dejaría que lo maneje el div padre (en este caso, el div title). Pero el resultado me gustó mucho! :D

**Comment by mrichart** [comment]
Gracias! a ver ahora?

**Comment by despinoUY** [comment]
Le hice algún ajuste de CSS para adaptarse al no título y a la foto nueva. Además le di un reorden a algunas partes del archivo SASS. Pegale una vichada.

**Comment by mrichart** [comment]
revisado y aprobado! 
me queda la duda de si no quedará mejor el texto con un poco menos de ancho en la versión desktop. para que quede en dos líneas. podemos consultar en el grupo de telegram cualquier cosa.

**Comment by mrichart** [comment]
ok con el último commit. mergeo!
